# Generated by Django 3.2 on 2022-04-18 11:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=100)),
                ('batch', models.CharField(max_length=4)),
                ('message', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Scores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Ravenclaw', models.IntegerField(default=0)),
                ('Gryffindor', models.IntegerField(default=0)),
                ('Hufflepuff', models.IntegerField(default=0)),
                ('Slytherin', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('score', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('eventnum', models.IntegerField(default=0)),
                ('winnerscore', models.IntegerField(default=0, verbose_name='Winner Score')),
                ('firstrunnerscore', models.IntegerField(default=0, verbose_name='First Runner up Score')),
                ('secondrunnerscore', models.IntegerField(default=0, verbose_name='Second Runner Up Score')),
                ('thirdrunnerscore', models.IntegerField(default=0, verbose_name='Third Runner Up Score')),
                ('penalty', models.CharField(max_length=100)),
                ('startdate', models.DateField()),
                ('enddate', models.DateField()),
                ('status', models.CharField(choices=[('C', 'Completed'), ('O', 'Ongoing'), ('U', 'Upcoming')], default='U', max_length=1)),
                ('about', models.TextField(max_length=500)),
                ('firstrunner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='event_firstrunner', to='home.team', verbose_name='First Runner Up')),
                ('secondrunner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='event_secondrunner', to='home.team', verbose_name='Second Runner Up')),
                ('thirdrunner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='event_thirdrunner', to='home.team', verbose_name='Third Runner Up')),
                ('winner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='event_winner', to='home.team', verbose_name='Winner')),
            ],
        ),
    ]
