# Generated by Django 3.2 on 2022-04-18 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='penalty',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
