# Generated by Django 3.2 on 2022-04-18 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_event_penalty'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='image',
            field=models.URLField(default='http://cdn.avirbhav.tech/avirbhav.jpeg'),
        ),
        migrations.AddField(
            model_name='event',
            name='slug',
            field=models.SlugField(default='avirbhav-event<django.db.models.fields.IntegerField>', unique=True),
        ),
    ]
